apiVersion: fn.kptgen.dev/v1alpha1
kind: NADRendererConfig
metadata:
  name: nad-renderer-config
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  defaultCNIType: macvlan
  defaultIPAMType: whereabouts
  namingTemplate: "{{ .NetworkName }}-net"
  namespaceIsolation: true
